# Generated by Django 4.2.7 on 2025-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('importance', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('work', 'Work'), ('fun', 'Fun'), ('research', 'Research')], default='work', max_length=20)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['importance'],
            },
        ),
    ]
