# Generated by Django 4.2.7 on 2025-08-02 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('categories', models.CharField(blank=True, max_length=200)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
