# Generated by Django 4.2.7 on 2025-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medium_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sciprofiles_url',
            field=models.URLField(blank=True),
        ),
    ]
