# Generated by Django 4.2.7 on 2025-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='publications/')),
                ('abstract', models.TextField(blank=True)),
                ('bibtex', models.TextField(blank=True)),
                ('selected', models.BooleanField(default=False)),
                ('preview_image', models.ImageField(blank=True, upload_to='publications/previews/')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
